// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qMKbWqzZjuHb1yLhCiN5Mq
// Component: WbcFyNRVknUx
import * as React from "react";
import { useRouter } from "next/router";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qMKbWqzZjuHb1yLhCiN5Mq/projectcss
import sty from "./PlasmicNavMenuItem.module.css"; // plasmic-import: WbcFyNRVknUx/css

createPlasmicElementProxy;

export const PlasmicNavMenuItem__VariantProps = new Array();

export const PlasmicNavMenuItem__ArgProps = new Array(
  "title",
  "children",
  "isMenuItemIconVisible"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavMenuItem__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          isMenuItemIconVisible: true
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <Stack__
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(() => {
          try {
            return $props.isMenuItemIconVisible;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })()
          ? renderPlasmicSlot({
              defaultContents: (
                <svg
                  className={classNames(projectcss.all, sty.svg___2HYcV)}
                  role={"img"}
                />
              ),

              value: args.children
            })
          : null}
        {(() => {
          try {
            return $props.title;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <nav
            data-plasmic-name={"menuItemTitle"}
            data-plasmic-override={overrides.menuItemTitle}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.menuItemTitle
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.title;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "Dashboard";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </nav>
        ) : null}
      </Stack__>
    </Stack__>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "menuItemTitle"],
  freeBox: ["freeBox", "menuItemTitle"],
  menuItemTitle: ["menuItemTitle"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavMenuItem__ArgProps,
          internalVariantPropNames: PlasmicNavMenuItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavMenuItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavMenuItem";
  } else {
    func.displayName = `PlasmicNavMenuItem.${nodeName}`;
  }
  return func;
}

export const PlasmicNavMenuItem = Object.assign(
  // Top-level PlasmicNavMenuItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    menuItemTitle: makeNodeComponent("menuItemTitle"),
    // Metadata about props expected for PlasmicNavMenuItem
    internalVariantProps: PlasmicNavMenuItem__VariantProps,
    internalArgProps: PlasmicNavMenuItem__ArgProps
  }
);

export default PlasmicNavMenuItem;
/* prettier-ignore-end */
