// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qMKbWqzZjuHb1yLhCiN5Mq
// Component: 14UlPLnVBmr4
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  initializeCodeComponentStates,
  initializePlasmicStates,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import MainPageLayout from "../../MainPageLayout"; // plasmic-import: bCVUuc7VYiYw/component
import Me from "../../Me"; // plasmic-import: M7n-Yi6ESK-n/component
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import Button2 from "../../Button2"; // plasmic-import: lci14Q3sXnn8/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qMKbWqzZjuHb1yLhCiN5Mq/projectcss
import sty from "./PlasmicTenantsPage.module.css"; // plasmic-import: 14UlPLnVBmr4/css
import { getUser as __fn_user__getUser } from "../../../utils/user"; // plasmic-import: user.getUser/customFunction

createPlasmicElementProxy;

export const PlasmicTenantsPage__VariantProps = new Array();

export const PlasmicTenantsPage__ArgProps = new Array();

const $$ = {
  user: {
    getUser: __fn_user__getUser
  }
};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTenantsPage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "updateProfileForm.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        refName: "updateProfileForm",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "updateProfileForm.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,
        refName: "updateProfileForm",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "profileEmail.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $$.user.getUser().email;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "profileMsisdn.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $$.user.getUser().msisdn;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "profileFirstName.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $$.user.getUser().msisdn;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "profileLastName.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $$.user.getUser().msisdn;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicTenantsPage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicTenantsPage.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicTenantsPage.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <MainPageLayout
            data-plasmic-name={"mainPageLayout"}
            data-plasmic-override={overrides.mainPageLayout}
            className={classNames("__wab_instance", sty.mainPageLayout)}
          >
            <h4
              data-plasmic-name={"h4"}
              data-plasmic-override={overrides.h4}
              className={classNames(
                projectcss.all,
                projectcss.h4,
                projectcss.__wab_text,
                sty.h4
              )}
            >
              {"Tenants"}
            </h4>
            <dd
              data-plasmic-name={"dd"}
              data-plasmic-override={overrides.dd}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.dd
              )}
            >
              {"Update your profile by filling in the form below."}
            </dd>
            <div className={classNames(projectcss.all, sty.freeBox__eAgKc)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__l49SD)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__sbsDh)}
                >
                  <Me
                    data-plasmic-name={"me"}
                    data-plasmic-override={overrides.me}
                    className={classNames("__wab_instance", sty.me)}
                    large={true}
                  />

                  {(() => {
                    const child$Props = {
                      className: classNames(
                        "__wab_instance",
                        sty.updateProfileForm
                      ),
                      extendedOnValuesChange:
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "value",
                          ["updateProfileForm", "value"],
                          FormWrapper_Helpers
                        ),
                      formItems: [
                        { label: "Name", name: "name", inputType: "Text" },
                        {
                          label: "Message",
                          name: "message",
                          inputType: "Text Area"
                        }
                      ],

                      labelCol: { span: 8, horizontalOnly: true },
                      layout: "vertical",
                      mode: "advanced",
                      onIsSubmittingChange:
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "isSubmitting",
                          ["updateProfileForm", "isSubmitting"],
                          FormWrapper_Helpers
                        ),
                      ref: ref => {
                        $refs["updateProfileForm"] = ref;
                      },
                      submitSlot: null,
                      wrapperCol: { span: 16, horizontalOnly: true }
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "updateProfileForm.value"
                        },
                        {
                          name: "isSubmitting",
                          plasmicStateName: "updateProfileForm.isSubmitting"
                        }
                      ],

                      [],
                      FormWrapper_Helpers ?? {},
                      child$Props
                    );
                    return (
                      <FormWrapper
                        data-plasmic-name={"updateProfileForm"}
                        data-plasmic-override={overrides.updateProfileForm}
                        {...child$Props}
                      >
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__umG5L
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__mqm7C
                            )}
                          >
                            <sub
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.sub___3RoTg
                              )}
                            >
                              {"Email address"}
                            </sub>
                            {(() => {
                              const child$Props = {
                                className: classNames(
                                  projectcss.all,
                                  projectcss.input,
                                  sty.profileEmail
                                ),
                                disabled: true,
                                onChange: e => {
                                  generateStateOnChangeProp($state, [
                                    "profileEmail",
                                    "value"
                                  ])(e.target.value);
                                },
                                placeholder: "Your registered email address",
                                ref: ref => {
                                  $refs["profileEmail"] = ref;
                                },
                                size: 1,
                                type: "email",
                                value:
                                  generateStateValueProp($state, [
                                    "profileEmail",
                                    "value"
                                  ]) ?? ""
                              };
                              initializePlasmicStates(
                                $state,
                                [
                                  {
                                    name: "profileEmail.value",
                                    initFunc: ({ $props, $state, $queries }) =>
                                      (() => {
                                        try {
                                          return $$.user.getUser().email;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return undefined;
                                          }
                                          throw e;
                                        }
                                      })()
                                  }
                                ],

                                []
                              );
                              return (
                                <input
                                  data-plasmic-name={"profileEmail"}
                                  data-plasmic-override={overrides.profileEmail}
                                  {...child$Props}
                                />
                              );
                            })()}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__rbA20
                            )}
                          >
                            <sub
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.sub__wrQi
                              )}
                            >
                              {"Phone number"}
                            </sub>
                            {(() => {
                              const child$Props = {
                                className: classNames(
                                  projectcss.all,
                                  projectcss.input,
                                  sty.profileMsisdn
                                ),
                                onChange: e => {
                                  generateStateOnChangeProp($state, [
                                    "profileMsisdn",
                                    "value"
                                  ])(e.target.value);
                                },
                                placeholder: "Your active phone number",
                                ref: ref => {
                                  $refs["profileMsisdn"] = ref;
                                },
                                size: 1,
                                type: "email",
                                value:
                                  generateStateValueProp($state, [
                                    "profileMsisdn",
                                    "value"
                                  ]) ?? ""
                              };
                              initializePlasmicStates(
                                $state,
                                [
                                  {
                                    name: "profileMsisdn.value",
                                    initFunc: ({ $props, $state, $queries }) =>
                                      (() => {
                                        try {
                                          return $$.user.getUser().msisdn;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return undefined;
                                          }
                                          throw e;
                                        }
                                      })()
                                  }
                                ],

                                []
                              );
                              return (
                                <input
                                  data-plasmic-name={"profileMsisdn"}
                                  data-plasmic-override={
                                    overrides.profileMsisdn
                                  }
                                  {...child$Props}
                                />
                              );
                            })()}
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__b9VVa
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__rUk4M
                              )}
                            >
                              <sub
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.sub__wOkHi
                                )}
                              >
                                {"First name"}
                              </sub>
                              {(() => {
                                const child$Props = {
                                  className: classNames(
                                    projectcss.all,
                                    projectcss.input,
                                    sty.profileFirstName
                                  ),
                                  onChange: e => {
                                    generateStateOnChangeProp($state, [
                                      "profileFirstName",
                                      "value"
                                    ])(e.target.value);
                                  },
                                  placeholder: "First name",
                                  ref: ref => {
                                    $refs["profileFirstName"] = ref;
                                  },
                                  size: 1,
                                  type: "email",
                                  value:
                                    generateStateValueProp($state, [
                                      "profileFirstName",
                                      "value"
                                    ]) ?? ""
                                };
                                initializePlasmicStates(
                                  $state,
                                  [
                                    {
                                      name: "profileFirstName.value",
                                      initFunc: ({
                                        $props,
                                        $state,
                                        $queries
                                      }) =>
                                        (() => {
                                          try {
                                            return $$.user.getUser().msisdn;
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return undefined;
                                            }
                                            throw e;
                                          }
                                        })()
                                    }
                                  ],

                                  []
                                );
                                return (
                                  <input
                                    data-plasmic-name={"profileFirstName"}
                                    data-plasmic-override={
                                      overrides.profileFirstName
                                    }
                                    {...child$Props}
                                  />
                                );
                              })()}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__fbIeF
                              )}
                            >
                              <sub
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.sub__qOaka
                                )}
                              >
                                {"Last name"}
                              </sub>
                              {(() => {
                                const child$Props = {
                                  className: classNames(
                                    projectcss.all,
                                    projectcss.input,
                                    sty.profileLastName
                                  ),
                                  onChange: e => {
                                    generateStateOnChangeProp($state, [
                                      "profileLastName",
                                      "value"
                                    ])(e.target.value);
                                  },
                                  placeholder: "Last name",
                                  ref: ref => {
                                    $refs["profileLastName"] = ref;
                                  },
                                  size: 1,
                                  type: "email",
                                  value:
                                    generateStateValueProp($state, [
                                      "profileLastName",
                                      "value"
                                    ]) ?? ""
                                };
                                initializePlasmicStates(
                                  $state,
                                  [
                                    {
                                      name: "profileLastName.value",
                                      initFunc: ({
                                        $props,
                                        $state,
                                        $queries
                                      }) =>
                                        (() => {
                                          try {
                                            return $$.user.getUser().msisdn;
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return undefined;
                                            }
                                            throw e;
                                          }
                                        })()
                                    }
                                  ],

                                  []
                                );
                                return (
                                  <input
                                    data-plasmic-name={"profileLastName"}
                                    data-plasmic-override={
                                      overrides.profileLastName
                                    }
                                    {...child$Props}
                                  />
                                );
                              })()}
                            </div>
                          </Stack__>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__mA3Mk
                          )}
                        >
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2__fEcSw
                            )}
                            endIcon={
                              <svg
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___27J9
                                )}
                                role={"img"}
                              />
                            }
                            startIcon={
                              <svg
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ypr9Q
                                )}
                                role={"img"}
                              />
                            }
                            submitsForm={true}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___7CWzw
                              )}
                            >
                              {"Update profile"}
                            </div>
                          </Button2>
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2___4HtVq
                            )}
                            color={"link"}
                            endIcon={
                              <svg
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__mCrqy
                                )}
                                role={"img"}
                              />
                            }
                            onClick={async event => {
                              const $steps = {};
                              $steps["goToLogoutPage"] = true
                                ? (() => {
                                    const actionArgs = {
                                      destination: `/user/logout`
                                    };
                                    return (({ destination }) => {
                                      if (
                                        typeof destination === "string" &&
                                        destination.startsWith("#")
                                      ) {
                                        document
                                          .getElementById(destination.substr(1))
                                          .scrollIntoView({
                                            behavior: "smooth"
                                          });
                                      } else {
                                        __nextRouter?.push(destination);
                                      }
                                    })?.apply(null, [actionArgs]);
                                  })()
                                : undefined;
                              if (
                                $steps["goToLogoutPage"] != null &&
                                typeof $steps["goToLogoutPage"] === "object" &&
                                typeof $steps["goToLogoutPage"].then ===
                                  "function"
                              ) {
                                $steps["goToLogoutPage"] = await $steps[
                                  "goToLogoutPage"
                                ];
                              }
                            }}
                            startIcon={
                              <svg
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__hCdS1
                                )}
                                role={"img"}
                              />
                            }
                            submitsForm={false}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___9MjFr
                              )}
                            >
                              {"Sign out"}
                            </div>
                          </Button2>
                        </Stack__>
                      </FormWrapper>
                    );
                  })()}
                </Stack__>
              </Stack__>
              <div className={classNames(projectcss.all, sty.freeBox__i5XQh)} />
              <div className={classNames(projectcss.all, sty.freeBox__cDaBu)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8Sg87
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {"To sign in, you need to have an active "}
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"SECaaS"}
                    </span>
                    <React.Fragment>
                      {
                        " account. \n\nDon't have an account yet? Contact us at secaas@thano.id or click here and fill out a simple form. We'll contact you right away. "
                      }
                    </React.Fragment>
                  </React.Fragment>
                </div>
              </div>
            </div>
          </MainPageLayout>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "mainPageLayout",
    "h4",
    "dd",
    "me",
    "updateProfileForm",
    "profileEmail",
    "profileMsisdn",
    "profileFirstName",
    "profileLastName"
  ],

  mainPageLayout: [
    "mainPageLayout",
    "h4",
    "dd",
    "me",
    "updateProfileForm",
    "profileEmail",
    "profileMsisdn",
    "profileFirstName",
    "profileLastName"
  ],

  h4: ["h4"],
  dd: ["dd"],
  me: ["me"],
  updateProfileForm: [
    "updateProfileForm",
    "profileEmail",
    "profileMsisdn",
    "profileFirstName",
    "profileLastName"
  ],

  profileEmail: ["profileEmail"],
  profileMsisdn: ["profileMsisdn"],
  profileFirstName: ["profileFirstName"],
  profileLastName: ["profileLastName"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTenantsPage__ArgProps,
          internalVariantPropNames: PlasmicTenantsPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTenantsPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTenantsPage";
  } else {
    func.displayName = `PlasmicTenantsPage.${nodeName}`;
  }
  return func;
}

export const PlasmicTenantsPage = Object.assign(
  // Top-level PlasmicTenantsPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mainPageLayout: makeNodeComponent("mainPageLayout"),
    h4: makeNodeComponent("h4"),
    dd: makeNodeComponent("dd"),
    me: makeNodeComponent("me"),
    updateProfileForm: makeNodeComponent("updateProfileForm"),
    profileEmail: makeNodeComponent("profileEmail"),
    profileMsisdn: makeNodeComponent("profileMsisdn"),
    profileFirstName: makeNodeComponent("profileFirstName"),
    profileLastName: makeNodeComponent("profileLastName"),
    // Metadata about props expected for PlasmicTenantsPage
    internalVariantProps: PlasmicTenantsPage__VariantProps,
    internalArgProps: PlasmicTenantsPage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Tenants",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTenantsPage;
/* prettier-ignore-end */
