// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qMKbWqzZjuHb1yLhCiN5Mq
// Component: 4KAedDWbVyXh
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  initializeCodeComponentStates,
  initializePlasmicStates,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import MainPageLayout from "../../MainPageLayout"; // plasmic-import: bCVUuc7VYiYw/component
import Me from "../../Me"; // plasmic-import: M7n-Yi6ESK-n/component
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import Button2 from "../../Button2"; // plasmic-import: lci14Q3sXnn8/component
import { RichTable } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { tableHelpers as RichTable_Helpers } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: qMKbWqzZjuHb1yLhCiN5Mq/projectcss
import sty from "./PlasmicPropertiesPage.module.css"; // plasmic-import: 4KAedDWbVyXh/css
import { getUser as __fn_user__getUser } from "../../../utils/user"; // plasmic-import: user.getUser/customFunction

createPlasmicElementProxy;

export const PlasmicPropertiesPage__VariantProps = new Array();

export const PlasmicPropertiesPage__ArgProps = new Array();

const $$ = {
  user: {
    getUser: __fn_user__getUser
  }
};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPropertiesPage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "updateProfileForm.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        refName: "updateProfileForm",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "updateProfileForm.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,
        refName: "updateProfileForm",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "profileEmail.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $$.user.getUser().email;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "profileMsisdn.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $$.user.getUser().msisdn;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "profileFirstName.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $$.user.getUser().msisdn;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "profileLastName.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $$.user.getUser().msisdn;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "buildingsTable.selectedRowKey",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("selectedRowKey", RichTable_Helpers)
      },
      {
        path: "buildingsTable.selectedRow",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("selectedRow", RichTable_Helpers)
      },
      {
        path: "buildingsTable.selectedRows",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("selectedRows", RichTable_Helpers)
      },
      {
        path: "buildingsTable.selectedRowKeys",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("selectedRowKeys", RichTable_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicPropertiesPage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicPropertiesPage.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicPropertiesPage.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <MainPageLayout
            data-plasmic-name={"mainPageLayout"}
            data-plasmic-override={overrides.mainPageLayout}
            className={classNames("__wab_instance", sty.mainPageLayout)}
          >
            <h4
              data-plasmic-name={"h4"}
              data-plasmic-override={overrides.h4}
              className={classNames(
                projectcss.all,
                projectcss.h4,
                projectcss.__wab_text,
                sty.h4
              )}
            >
              {"Properties"}
            </h4>
            <dd
              data-plasmic-name={"dd"}
              data-plasmic-override={overrides.dd}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.dd
              )}
            >
              {""}
            </dd>
            <div className={classNames(projectcss.all, sty.freeBox___296Fk)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__vIl3F)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ebDUw)}
                >
                  <Me
                    data-plasmic-name={"me"}
                    data-plasmic-override={overrides.me}
                    className={classNames("__wab_instance", sty.me)}
                    large={true}
                  />

                  {(() => {
                    const child$Props = {
                      className: classNames(
                        "__wab_instance",
                        sty.updateProfileForm
                      ),
                      extendedOnValuesChange:
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "value",
                          ["updateProfileForm", "value"],
                          FormWrapper_Helpers
                        ),
                      formItems: [
                        { label: "Name", name: "name", inputType: "Text" },
                        {
                          label: "Message",
                          name: "message",
                          inputType: "Text Area"
                        }
                      ],

                      labelCol: { span: 8, horizontalOnly: true },
                      layout: "vertical",
                      mode: "advanced",
                      onIsSubmittingChange:
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "isSubmitting",
                          ["updateProfileForm", "isSubmitting"],
                          FormWrapper_Helpers
                        ),
                      ref: ref => {
                        $refs["updateProfileForm"] = ref;
                      },
                      submitSlot: null,
                      wrapperCol: { span: 16, horizontalOnly: true }
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "updateProfileForm.value"
                        },
                        {
                          name: "isSubmitting",
                          plasmicStateName: "updateProfileForm.isSubmitting"
                        }
                      ],

                      [],
                      FormWrapper_Helpers ?? {},
                      child$Props
                    );
                    return (
                      <FormWrapper
                        data-plasmic-name={"updateProfileForm"}
                        data-plasmic-override={overrides.updateProfileForm}
                        {...child$Props}
                      >
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fT36
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__uHjpB
                            )}
                          >
                            <sub
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.sub__yccgy
                              )}
                            >
                              {"Email address"}
                            </sub>
                            {(() => {
                              const child$Props = {
                                className: classNames(
                                  projectcss.all,
                                  projectcss.input,
                                  sty.profileEmail
                                ),
                                disabled: true,
                                onChange: e => {
                                  generateStateOnChangeProp($state, [
                                    "profileEmail",
                                    "value"
                                  ])(e.target.value);
                                },
                                placeholder: "Your registered email address",
                                ref: ref => {
                                  $refs["profileEmail"] = ref;
                                },
                                size: 1,
                                type: "email",
                                value:
                                  generateStateValueProp($state, [
                                    "profileEmail",
                                    "value"
                                  ]) ?? ""
                              };
                              initializePlasmicStates(
                                $state,
                                [
                                  {
                                    name: "profileEmail.value",
                                    initFunc: ({ $props, $state, $queries }) =>
                                      (() => {
                                        try {
                                          return $$.user.getUser().email;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return undefined;
                                          }
                                          throw e;
                                        }
                                      })()
                                  }
                                ],

                                []
                              );
                              return (
                                <input
                                  data-plasmic-name={"profileEmail"}
                                  data-plasmic-override={overrides.profileEmail}
                                  {...child$Props}
                                />
                              );
                            })()}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__uLMc
                            )}
                          >
                            <sub
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.sub__axvD0
                              )}
                            >
                              {"Phone number"}
                            </sub>
                            {(() => {
                              const child$Props = {
                                className: classNames(
                                  projectcss.all,
                                  projectcss.input,
                                  sty.profileMsisdn
                                ),
                                onChange: e => {
                                  generateStateOnChangeProp($state, [
                                    "profileMsisdn",
                                    "value"
                                  ])(e.target.value);
                                },
                                placeholder: "Your active phone number",
                                ref: ref => {
                                  $refs["profileMsisdn"] = ref;
                                },
                                size: 1,
                                type: "email",
                                value:
                                  generateStateValueProp($state, [
                                    "profileMsisdn",
                                    "value"
                                  ]) ?? ""
                              };
                              initializePlasmicStates(
                                $state,
                                [
                                  {
                                    name: "profileMsisdn.value",
                                    initFunc: ({ $props, $state, $queries }) =>
                                      (() => {
                                        try {
                                          return $$.user.getUser().msisdn;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return undefined;
                                          }
                                          throw e;
                                        }
                                      })()
                                  }
                                ],

                                []
                              );
                              return (
                                <input
                                  data-plasmic-name={"profileMsisdn"}
                                  data-plasmic-override={
                                    overrides.profileMsisdn
                                  }
                                  {...child$Props}
                                />
                              );
                            })()}
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__cdd7
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___77F
                              )}
                            >
                              <sub
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.sub__e6Ay2
                                )}
                              >
                                {"First name"}
                              </sub>
                              {(() => {
                                const child$Props = {
                                  className: classNames(
                                    projectcss.all,
                                    projectcss.input,
                                    sty.profileFirstName
                                  ),
                                  onChange: e => {
                                    generateStateOnChangeProp($state, [
                                      "profileFirstName",
                                      "value"
                                    ])(e.target.value);
                                  },
                                  placeholder: "First name",
                                  ref: ref => {
                                    $refs["profileFirstName"] = ref;
                                  },
                                  size: 1,
                                  type: "email",
                                  value:
                                    generateStateValueProp($state, [
                                      "profileFirstName",
                                      "value"
                                    ]) ?? ""
                                };
                                initializePlasmicStates(
                                  $state,
                                  [
                                    {
                                      name: "profileFirstName.value",
                                      initFunc: ({
                                        $props,
                                        $state,
                                        $queries
                                      }) =>
                                        (() => {
                                          try {
                                            return $$.user.getUser().msisdn;
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return undefined;
                                            }
                                            throw e;
                                          }
                                        })()
                                    }
                                  ],

                                  []
                                );
                                return (
                                  <input
                                    data-plasmic-name={"profileFirstName"}
                                    data-plasmic-override={
                                      overrides.profileFirstName
                                    }
                                    {...child$Props}
                                  />
                                );
                              })()}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__xlmu4
                              )}
                            >
                              <sub
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.sub__isj45
                                )}
                              >
                                {"Last name"}
                              </sub>
                              {(() => {
                                const child$Props = {
                                  className: classNames(
                                    projectcss.all,
                                    projectcss.input,
                                    sty.profileLastName
                                  ),
                                  onChange: e => {
                                    generateStateOnChangeProp($state, [
                                      "profileLastName",
                                      "value"
                                    ])(e.target.value);
                                  },
                                  placeholder: "Last name",
                                  ref: ref => {
                                    $refs["profileLastName"] = ref;
                                  },
                                  size: 1,
                                  type: "email",
                                  value:
                                    generateStateValueProp($state, [
                                      "profileLastName",
                                      "value"
                                    ]) ?? ""
                                };
                                initializePlasmicStates(
                                  $state,
                                  [
                                    {
                                      name: "profileLastName.value",
                                      initFunc: ({
                                        $props,
                                        $state,
                                        $queries
                                      }) =>
                                        (() => {
                                          try {
                                            return $$.user.getUser().msisdn;
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return undefined;
                                            }
                                            throw e;
                                          }
                                        })()
                                    }
                                  ],

                                  []
                                );
                                return (
                                  <input
                                    data-plasmic-name={"profileLastName"}
                                    data-plasmic-override={
                                      overrides.profileLastName
                                    }
                                    {...child$Props}
                                  />
                                );
                              })()}
                            </div>
                          </Stack__>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ybEd
                          )}
                        >
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2___3CSzI
                            )}
                            endIcon={
                              <svg
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__os4CO
                                )}
                                role={"img"}
                              />
                            }
                            startIcon={
                              <svg
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__qInGj
                                )}
                                role={"img"}
                              />
                            }
                            submitsForm={true}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__eoEj4
                              )}
                            >
                              {"Update profile"}
                            </div>
                          </Button2>
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2__wyFqf
                            )}
                            color={"link"}
                            endIcon={
                              <svg
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__gKWrD
                                )}
                                role={"img"}
                              />
                            }
                            onClick={async event => {
                              const $steps = {};
                              $steps["goToLogoutPage"] = true
                                ? (() => {
                                    const actionArgs = {
                                      destination: `/user/logout`
                                    };
                                    return (({ destination }) => {
                                      if (
                                        typeof destination === "string" &&
                                        destination.startsWith("#")
                                      ) {
                                        document
                                          .getElementById(destination.substr(1))
                                          .scrollIntoView({
                                            behavior: "smooth"
                                          });
                                      } else {
                                        __nextRouter?.push(destination);
                                      }
                                    })?.apply(null, [actionArgs]);
                                  })()
                                : undefined;
                              if (
                                $steps["goToLogoutPage"] != null &&
                                typeof $steps["goToLogoutPage"] === "object" &&
                                typeof $steps["goToLogoutPage"].then ===
                                  "function"
                              ) {
                                $steps["goToLogoutPage"] = await $steps[
                                  "goToLogoutPage"
                                ];
                              }
                            }}
                            startIcon={
                              <svg
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__dLp2M
                                )}
                                role={"img"}
                              />
                            }
                            submitsForm={false}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__fwuUy
                              )}
                            >
                              {"Sign out"}
                            </div>
                          </Button2>
                        </Stack__>
                      </FormWrapper>
                    );
                  })()}
                </Stack__>
              </Stack__>
              <div
                className={classNames(projectcss.all, sty.freeBox___2Stq7)}
              />

              <div className={classNames(projectcss.all, sty.freeBox___1N6G9)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yppsS
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {"To sign in, you need to have an active "}
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"SECaaS"}
                    </span>
                    <React.Fragment>
                      {
                        " account. \n\nDon't have an account yet? Contact us at secaas@thano.id or click here and fill out a simple form. We'll contact you right away. "
                      }
                    </React.Fragment>
                  </React.Fragment>
                </div>
              </div>
            </div>
            <h5
              data-plasmic-name={"h5"}
              data-plasmic-override={overrides.h5}
              className={classNames(
                projectcss.all,
                projectcss.h5,
                projectcss.__wab_text,
                sty.h5
              )}
            >
              {"Buildings"}
            </h5>
            {(() => {
              const child$Props = {
                className: classNames("__wab_instance", sty.buildingsTable),
                onRowSelectionChanged: async (...eventArgs) => {
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "selectedRowKey",
                    ["buildingsTable", "selectedRowKey"],
                    RichTable_Helpers
                  ).apply(null, eventArgs);
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "selectedRow",
                    ["buildingsTable", "selectedRow"],
                    RichTable_Helpers
                  ).apply(null, eventArgs);
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "selectedRows",
                    ["buildingsTable", "selectedRows"],
                    RichTable_Helpers
                  ).apply(null, eventArgs);
                  generateStateOnChangePropForCodeComponents(
                    $state,
                    "selectedRowKeys",
                    ["buildingsTable", "selectedRowKeys"],
                    RichTable_Helpers
                  ).apply(null, eventArgs);
                },
                scopeClassName: sty["buildingsTable__instance"],
                selectedRowKey: generateStateValueProp($state, [
                  "buildingsTable",
                  "selectedRowKey"
                ]),
                selectedRowKeys: generateStateValueProp($state, [
                  "buildingsTable",
                  "selectedRowKeys"
                ]),
                themeResetClassName: classNames(
                  projectcss.root_reset,
                  projectcss.root_reset_tags,
                  projectcss.plasmic_default_styles,
                  projectcss.plasmic_mixins,
                  projectcss.plasmic_tokens,
                  plasmic_antd_5_hostless_css.plasmic_tokens,
                  plasmic_plasmic_rich_components_css.plasmic_tokens
                )
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "selectedRowKey",
                    plasmicStateName: "buildingsTable.selectedRowKey"
                  },
                  {
                    name: "selectedRow",
                    plasmicStateName: "buildingsTable.selectedRow"
                  },
                  {
                    name: "selectedRows",
                    plasmicStateName: "buildingsTable.selectedRows"
                  },
                  {
                    name: "selectedRowKeys",
                    plasmicStateName: "buildingsTable.selectedRowKeys"
                  }
                ],

                [],
                RichTable_Helpers ?? {},
                child$Props
              );
              return (
                <RichTable
                  data-plasmic-name={"buildingsTable"}
                  data-plasmic-override={overrides.buildingsTable}
                  {...child$Props}
                />
              );
            })()}
          </MainPageLayout>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "mainPageLayout",
    "h4",
    "dd",
    "me",
    "updateProfileForm",
    "profileEmail",
    "profileMsisdn",
    "profileFirstName",
    "profileLastName",
    "h5",
    "buildingsTable"
  ],

  mainPageLayout: [
    "mainPageLayout",
    "h4",
    "dd",
    "me",
    "updateProfileForm",
    "profileEmail",
    "profileMsisdn",
    "profileFirstName",
    "profileLastName",
    "h5",
    "buildingsTable"
  ],

  h4: ["h4"],
  dd: ["dd"],
  me: ["me"],
  updateProfileForm: [
    "updateProfileForm",
    "profileEmail",
    "profileMsisdn",
    "profileFirstName",
    "profileLastName"
  ],

  profileEmail: ["profileEmail"],
  profileMsisdn: ["profileMsisdn"],
  profileFirstName: ["profileFirstName"],
  profileLastName: ["profileLastName"],
  h5: ["h5"],
  buildingsTable: ["buildingsTable"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPropertiesPage__ArgProps,
          internalVariantPropNames: PlasmicPropertiesPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPropertiesPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPropertiesPage";
  } else {
    func.displayName = `PlasmicPropertiesPage.${nodeName}`;
  }
  return func;
}

export const PlasmicPropertiesPage = Object.assign(
  // Top-level PlasmicPropertiesPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mainPageLayout: makeNodeComponent("mainPageLayout"),
    h4: makeNodeComponent("h4"),
    dd: makeNodeComponent("dd"),
    me: makeNodeComponent("me"),
    updateProfileForm: makeNodeComponent("updateProfileForm"),
    profileEmail: makeNodeComponent("profileEmail"),
    profileMsisdn: makeNodeComponent("profileMsisdn"),
    profileFirstName: makeNodeComponent("profileFirstName"),
    profileLastName: makeNodeComponent("profileLastName"),
    h5: makeNodeComponent("h5"),
    buildingsTable: makeNodeComponent("buildingsTable"),
    // Metadata about props expected for PlasmicPropertiesPage
    internalVariantProps: PlasmicPropertiesPage__VariantProps,
    internalArgProps: PlasmicPropertiesPage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Properties",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPropertiesPage;
/* prettier-ignore-end */
